on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Generate GeoIP2 database
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          if [ -f go.mod ]; then
            go mod tidy
          else
            go get -v -t -d ./...
          fi

      - name: Create dist folder
        run: mkdir -p dist

      - name: Make build.sh executable and compile
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Download China IP lists
        run: |
          # Adding 'set -euo pipefail' for robust error handling in this step
          set -euo pipefail
          curl -LR -o dist/ipip_net.txt "https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt"
          curl -LR -o dist/chunzhen.txt "https://raw.githubusercontent.com/metowolf/iplist/master/data/country/CN.txt"
          curl -LR -o dist/china6.txt "https://gaoyifan.github.io/china-operator-ip/china6.txt"

      - name: Merge and deduplicate IP lists
        run: |
          awk '{print}' dist/*.txt > dist/merge.txt
          awk '!seen[$0]++' dist/merge.txt > dist/CN-ip-cidr.txt

      - name: Generate GeoIP2 database
        run: |
          cd dist
          ./ipip2mmdb -s ./CN-ip-cidr.txt -d Country.mmdb

      - name: Install sing-box
        env:
          SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.8.0-rc.7/sing-box_1.8.0-rc.7_linux_amd64.deb"
        run: |
          set -Eeuo pipefail
          wget -O sing-box.deb $SING_BOX_DEB_URL
          sudo dpkg -i sing-box.deb

      - name: Convert CN-ip-cidr.txt to singbox.json
        run: |
          jq -Rn '
            [inputs | select(length > 0)] as $cidr
            | {
                version: 1,
                rules: [
                  { ip_cidr: $cidr }
                ]
              }
          ' < dist/CN-ip-cidr.txt > dist/singbox.json

      - name: Compile sing-box rule-set
        run: |
          sing-box rule-set compile --output dist/geoip.srs dist/singbox.json

      - name: Prepare geoip branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git reset --hard
          git clean -dfX

          git fetch origin

          git switch --orphan release-geoip

          # rm -rf ./*

          cp dist/CN-ip-cidr.txt .
          cp dist/Country.mmdb .
          cp dist/geoip.srs .

          git add CN-ip-cidr.txt Country.mmdb geoip.srs
          git commit -m "Updated at $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

          git branch -M geoip

      - name: Push to geoip branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: geoip
          force: true